export const AUTH_LOGIN_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED = 'AUTH_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const POSTS_RESET = 'POST_RESET';

export const LOAD_AND_RESET = 'LOAD_AND_RESET';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL';
export const POST_RESET = 'POST_RESET';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const SEARCH_EDIT_POST = 'SEARCH_EDIT_POST';
export const START_EDIT_POST = 'START_EDIT_POST';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const PROFILE_RESET = 'PROFILE_RESET';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_STATUS_START = 'SET_STATUS_START';
export const SET_STATUS_SUCCESS = 'SET_STATUS_SUCCESS';
export const SET_STATUS_FAIL = 'SET_STATUS_FAIL';
